name: GitHub Actions Demo Pullrequest
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: ['pull_request']
jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Copy example env file
        run: |
          cp .env.example .env
      - name: Start Docker Compose
        uses: hoverkraft-tech/compose-action@v2.0.1
        with:
          compose-file: |
            ./docker-compose.yml
            ./docker-compose.test.yml
      - name: Run Laravel Tests
        run: |
          docker-compose exec app php artisan test
